plugins:
  landing_contact_phone_enabled:
    default: false
    client: true
  landing_contact_email:
    default: 'contact@civically.io'
  landing_visible_locales:
    default: 'ar,zh_CN,en,es,fr,ru'
    client: true
